name: Remove

on:
  workflow_dispatch: # And manually on button click
  pull_request:
    types: [closed]
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
      - name: Slug
        uses: rlespinasse/github-slug-action@v4

      - name: Create Removing Monitor
        run: |
          # synopsys: remove docroot <slug>
          mkdir -p doc && echo "remove docroot ${GITHUB_REPOSITORY_NAME_PART_SLUG}" > "doc/monitor_${GITHUB_RUN_ID}.txt"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: doc
